brew install apache-spark
brew install aspcud
brew install awscli
brew install azure-cli
brew install camlp4
brew install clasp
brew install clingo
brew install cmake
brew install emacs
brew install faac
brew install fdk-aac
brew install ffmpeg
brew install fontconfig
brew install freetype
brew install fzf
brew install gd
brew install gdbm
brew install gettext
brew install git
brew install gmp
brew install gradle
brew install graphviz
brew install grep
brew install gringo
brew install hadoop
brew install heroku
brew install heroku-node
brew install htop
brew install icu4c
brew install iftop
brew install infer
brew install isl
brew install jpeg
brew install lame
brew install libav
brew install libevent
brew install libidn2
brew install libmpc
brew install libogg
brew install libpng
brew install libtiff
brew install libtool
brew install libunistring
brew install libvorbis
brew install libvpx
brew install libyaml
brew install libzip
brew install maven
brew install most
brew install mpfr
brew install mysql
brew install netcat
brew install node
brew install ocaml
brew install ocamlbuild
brew install opam
brew install openssl
brew install openssl@1.1
brew install opus
brew install pcre
brew install perl
brew install pkg-config
brew install python
brew install python3
brew install readline
brew install reattach-to-user-namespace
brew install ruby
brew install s-lang
brew install spin
brew install sqlite
brew install telnet
brew install terraform
brew install the_silver_searcher
brew install tldr
brew install tmux
brew install vim
brew install webp
brew install wget
brew install wrk
brew install x264
brew install xvid
brew install xz
