brew install adobe-acrobat-reader
brew install adobe-air
brew install adobe-connect
brew install airflow
brew install alfred
brew install anaconda
brew install android-file-transfer
brew install appcleaner
brew install atom
brew install bettertouchtool
brew install ccleaner
brew install clion
brew install cmake
brew install cyberduck
brew install dash
brew install firefox
brew install github-desktop
brew install google-chrome
brew install iina
brew install intellij-idea
brew install istat-menus
brew install iterm2
brew install league-of-legends
brew install macvim
brew install mipony
brew install pandora
brew install postico
brew install postman
brew install pycharm
brew install qbittorrent
brew install simple-comic
brew install skype
brew install slack
brew install sourcetree
brew install spotify
brew install steam
brew install the-unarchiver
brew install visual-studio-code
brew install vlc
brew install wewechat
brew install xquartz
